print("_" *35)
print("Tugas 1 SISOP Kelas-B")
print("_" *35)
print("Nama: Naufal Baihaqi Moerrin")
print("NPM: 21083010077")
print("_" *35)
print("Notes:")
print("_" *35)
print("Halo dunia!")
print("Ini adalah Script Python pertamaku di Linux!")
